#ifndef EXT_NOISELIB_LIB_GENERATOR_OBJECTS_TREES_DEFAULTS_REDMUSHROOMTREE_H_
#define EXT_NOISELIB_LIB_GENERATOR_OBJECTS_TREES_DEFAULTS_REDMUSHROOMTREE_H_

#include "BrownMushroomTree.h"

class RedMushroomTree : public BrownMushroomTree {
 public:
  RedMushroomTree();
};

#endif //EXT_NOISELIB_LIB_GENERATOR_OBJECTS_TREES_DEFAULTS_REDMUSHROOMTREE_H_
