#ifndef VANILLAGENERATOR_SRC_GENERATOR_GENERATOR_H_
#define VANILLAGENERATOR_SRC_GENERATOR_GENERATOR_H_

#define COORDINATE_SCALE 684.412
#define HEIGHT_SCALE 684.412
#define DEFAULT_NOISE_SCALE 1.0
#define HEIGHT_NOISE_SCALE_X 200.0
#define HEIGHT_NOISE_SCALE_Z 200.0
#define DETAIL_NOISE_SCALE_X 80.0
#define DETAIL_NOISE_SCALE_Y 160.0
#define DETAIL_NOISE_SCALE_Z 80.0
#define SURFACE_SCALE 0.0625
#define BASE_SIZE 8.5
#define STRETCH_Y 12.0
#define BIOME_HEIGHT_OFFSET 0.0
#define BIOME_HEIGHT_WEIGHT 1.0
#define BIOME_SCALE_OFFSET 0.0
#define BIOME_SCALE_WEIGHT 1.0
#define DENSITY_FILL_MODE 0
#define DENSITY_FILL_SEA_MODE 0
#define DENSITY_FILL_OFFSET 0.0

struct Octaves {

};

class Generator {
 public:
  Generator();

  Octaves octaves_;
};

#endif //VANILLAGENERATOR_SRC_GENERATOR_GENERATOR_H_
