#ifndef EXT_VANILLAGENERATOR_LIB_POCKETMINE_BIOMELIST_H_
#define EXT_VANILLAGENERATOR_LIB_POCKETMINE_BIOMELIST_H_

#define OCEAN 0
#define PLAINS 1
#define DESERT 2
#define EXTREME_HILLS 3
#define FOREST 4
#define TAIGA 5
#define SWAMPLAND 6
#define RIVER 7
#define HELL 8
#define SKY 9
#define FROZEN_OCEAN 10
#define FROZEN_RIVER 11
#define ICE_PLAINS 12
#define ICE_MOUNTAINS 13
#define MUSHROOM_ISLAND 14
#define MUSHROOM_SHORE 15
#define BEACH 16
#define DESERT_HILLS 17
#define FOREST_HILLS 18
#define TAIGA_HILLS 19
#define SMALL_MOUNTAINS 20
#define JUNGLE 21
#define JUNGLE_HILLS 22
#define JUNGLE_EDGE 23
#define DEEP_OCEAN 24
#define STONE_BEACH 25
#define COLD_BEACH 26
#define BIRCH_FOREST 27
#define BIRCH_FOREST_HILLS 28
#define ROOFED_FOREST 29
#define COLD_TAIGA 30
#define COLD_TAIGA_HILLS 31
#define MEGA_TAIGA 32
#define MEGA_TAIGA_HILLS 33
#define EXTREME_HILLS_PLUS 34
#define SAVANNA 35
#define SAVANNA_PLATEAU 36
#define MESA 37
#define MESA_PLATEAU_FOREST 38
#define MESA_PLATEAU 39

#define SUNFLOWER_PLAINS 129
#define DESERT_MOUNTAINS 130
#define EXTREME_HILLS_MOUNTAINS 131
#define FLOWER_FOREST 132
#define TAIGA_MOUNTAINS 133
#define SWAMPLAND_MOUNTAINS 134

#define ICE_PLAINS_SPIKES 140

#define JUNGLE_MOUNTAINS 149

#define JUNGLE_EDGE_MOUNTAINS 151

#define BIRCH_FOREST_MOUNTAINS 155
#define BIRCH_FOREST_HILLS_MOUNTAINS 156
#define ROOFED_FOREST_MOUNTAINS 157
#define COLD_TAIGA_MOUNTAINS 158

#define MEGA_SPRUCE_TAIGA 160
#define MEGA_SPRUCE_TAIGA_HILLS 161
#define EXTREME_HILLS_PLUS_MOUNTAINS 162
#define SAVANNA_MOUNTAINS 163
#define SAVANNA_PLATEAU_MOUNTAINS 164
#define MESA_BRYCE 165
#define MESA_PLATEAU_FOREST_MOUNTAINS 166
#define MESA_PLATEAU_MOUNTAINS 167

#define ALL_BIOMES { \
    OCEAN, \
    PLAINS, \
    DESERT, \
    EXTREME_HILLS, \
    FOREST, \
    TAIGA, \
    SWAMPLAND, \
    RIVER, \
    HELL, \
    SKY, \
    FROZEN_OCEAN, \
    FROZEN_RIVER, \
    ICE_PLAINS, \
    ICE_MOUNTAINS, \
    MUSHROOM_ISLAND, \
    MUSHROOM_SHORE, \
    BEACH, \
    DESERT_HILLS, \
    FOREST_HILLS, \
    TAIGA_HILLS, \
    SMALL_MOUNTAINS, \
    JUNGLE, \
    JUNGLE_HILLS, \
    JUNGLE_EDGE, \
    DEEP_OCEAN, \
    STONE_BEACH, \
    COLD_BEACH, \
    BIRCH_FOREST, \
    BIRCH_FOREST_HILLS, \
    ROOFED_FOREST, \
    COLD_TAIGA, \
    COLD_TAIGA_HILLS, \
    MEGA_TAIGA, \
    MEGA_TAIGA_HILLS, \
    EXTREME_HILLS_PLUS, \
    SAVANNA, \
    SAVANNA_PLATEAU, \
    MESA, \
    MESA_PLATEAU_FOREST, \
    MESA_PLATEAU, \
    SUNFLOWER_PLAINS, \
    DESERT_MOUNTAINS, \
    EXTREME_HILLS_MOUNTAINS, \
    FLOWER_FOREST, \
    TAIGA_MOUNTAINS, \
    SWAMPLAND_MOUNTAINS, \
    ICE_PLAINS_SPIKES, \
    JUNGLE_MOUNTAINS, \
    JUNGLE_EDGE_MOUNTAINS, \
    BIRCH_FOREST_MOUNTAINS, \
    BIRCH_FOREST_HILLS_MOUNTAINS, \
    ROOFED_FOREST_MOUNTAINS, \
    COLD_TAIGA_MOUNTAINS, \
    MEGA_SPRUCE_TAIGA, \
    MEGA_SPRUCE_TAIGA_HILLS, \
    EXTREME_HILLS_PLUS_MOUNTAINS, \
    SAVANNA_MOUNTAINS, \
    SAVANNA_PLATEAU_MOUNTAINS, \
    MESA_BRYCE, \
    MESA_PLATEAU_FOREST_MOUNTAINS, \
    MESA_PLATEAU_MOUNTAINS     \
}

#endif // EXT_VANILLAGENERATOR_LIB_POCKETMINE_BIOMELIST_H_
