#include <algorithm>
#include <stdexcept>
#include <string>
#include <blocks/Blocks.h>
#include <math/Facing.h>

using namespace block;

Block::Block(unsigned short block, unsigned char block_meta) : block_id_(block), meta_(block_meta) {}

unsigned int Block::GetFullId() const {
  return (block_id_ << 4) | meta_;
}

unsigned short Block::GetId() const {
  return block_id_;
}

unsigned char Block::GetMeta() const {
  return meta_;
}

bool Block::IsObjectNull() const {
  return GetId() == 0 && GetMeta() == 0;
}

bool Block::operator==(const Block &rhs) const {
  return rhs.GetId() == GetId() && rhs.GetMeta() == GetMeta();
}

bool Block::operator!=(const Block &rhs) const {
  return rhs.GetId() != GetId();
}

unsigned char Block::WriteLegacyHorizontalFacing(int facing) {
  switch (facing) {
    case Facing::SOUTH: return 0;
    case Facing::WEST: return 1;
    case Facing::NORTH: return 2;
    case Facing::EAST: return 3;
    default:return 0;
  }
}

unsigned char Block::WriteVineBlockFacingMeta(int facing) {
  switch (facing) {
    case Facing::NORTH: return 4;
    case Facing::SOUTH: return 1;
    case Facing::WEST: return 2;
    case Facing::EAST: return 8;
    default:return 0;
  }
}

void Block::RegisterBlock(int id, int meta) {
  unsigned int index = (id << INTERNAL_METADATA_BITS) | meta;

  if (Block::blocks_[index] != nullptr) {
    Block *block = Block::blocks_[index];

    if (block->GetFullId() == index) {
      throw std::invalid_argument(std::to_string(id) + ":" + std::to_string(meta) + " is already mapped");
    }
  }

  Block::blocks_[index] = new Block(id, meta);
}

Block const *Block::GetBlockIdAndMeta(unsigned short id, unsigned char meta) {
  return GetBlockFromFullId((id << 4) | meta);
}

const Block *Block::GetBlockFromFullId(unsigned int fullBlockId) {
  if (fullBlockId < (sizeof(blocks_) / sizeof(blocks_[0]))) {
    return blocks_[fullBlockId];
  }

  return nullptr;
}

void Block::RegisterAllBlocks() {
  if (initialized_) return;
  initialized_ = true;

  std::fill(Block::blocks_, Block::blocks_ + sizeof(Block::blocks_) / sizeof(Block::blocks_[0]), nullptr);

  RegisterBlock(BlockIds::ACACIA_BUTTON, 0);
  RegisterBlock(BlockIds::ACACIA_DOOR_BLOCK, 0);
  RegisterBlock(BlockIds::FENCE, 4);
  RegisterBlock(BlockIds::ACACIA_FENCE_GATE, 0);
  RegisterBlock(BlockIds::LEAVES2, 0);
  RegisterBlock(BlockIds::LOG2, 0);
  RegisterBlock(BlockIds::PLANKS, 4);
  RegisterBlock(BlockIds::ACACIA_PRESSURE_PLATE, 0);
  RegisterBlock(BlockIds::SAPLING, 4);
  RegisterBlock(BlockIds::ACACIA_STANDING_SIGN, 0);
  RegisterBlock(BlockIds::WOODEN_SLAB, 4);
  RegisterBlock(BlockIds::ACACIA_STAIRS, 0);
  RegisterBlock(BlockIds::ACACIA_TRAPDOOR, 0);
  RegisterBlock(BlockIds::ACACIA_WALL_SIGN, 2);
  RegisterBlock(BlockIds::WOOD, 4);
  RegisterBlock(BlockIds::ACTIVATOR_RAIL, 0);
  RegisterBlock(BlockIds::AIR, 0);
  RegisterBlock(BlockIds::BROWN_MUSHROOM_BLOCK, 15);
  RegisterBlock(BlockIds::POPPY, 2);
  RegisterBlock(BlockIds::STONE, 5);
  RegisterBlock(BlockIds::STONE_SLAB3, 3);
  RegisterBlock(BlockIds::ANDESITE_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 4);
  RegisterBlock(BlockIds::ANVIL, 0);
  RegisterBlock(BlockIds::POPPY, 3);
  RegisterBlock(BlockIds::BAMBOO, 0);
  RegisterBlock(BlockIds::BAMBOO_SAPLING, 0);
  RegisterBlock(BlockIds::STANDING_BANNER, 0);
  RegisterBlock(BlockIds::BARREL, 0);
  RegisterBlock(BlockIds::BARRIER, 0);
  RegisterBlock(BlockIds::BEACON, 0);
  RegisterBlock(BlockIds::BED_BLOCK, 0);
  RegisterBlock(BlockIds::BEDROCK, 0);
  RegisterBlock(BlockIds::BEETROOT_BLOCK, 0);
  RegisterBlock(BlockIds::BELL, 0);
  RegisterBlock(BlockIds::BIRCH_BUTTON, 0);
  RegisterBlock(BlockIds::BIRCH_DOOR_BLOCK, 0);
  RegisterBlock(BlockIds::FENCE, 2);
  RegisterBlock(BlockIds::BIRCH_FENCE_GATE, 0);
  RegisterBlock(BlockIds::LEAVES, 2);
  RegisterBlock(BlockIds::LOG, 2);
  RegisterBlock(BlockIds::PLANKS, 2);
  RegisterBlock(BlockIds::BIRCH_PRESSURE_PLATE, 0);
  RegisterBlock(BlockIds::SAPLING, 2);
  RegisterBlock(BlockIds::BIRCH_STANDING_SIGN, 0);
  RegisterBlock(BlockIds::WOODEN_SLAB, 2);
  RegisterBlock(BlockIds::BIRCH_STAIRS, 0);
  RegisterBlock(BlockIds::BIRCH_TRAPDOOR, 0);
  RegisterBlock(BlockIds::BIRCH_WALL_SIGN, 2);
  RegisterBlock(BlockIds::WOOD, 2);
  RegisterBlock(BlockIds::BLACK_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::BLAST_FURNACE, 2);
  RegisterBlock(BlockIds::BLUE_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::BLUE_ICE, 0);
  RegisterBlock(BlockIds::POPPY, 1);
  RegisterBlock(BlockIds::COLORED_TORCH_BP, 5);
  RegisterBlock(BlockIds::BONE_BLOCK, 0);
  RegisterBlock(BlockIds::BOOKSHELF, 0);
  RegisterBlock(BlockIds::BREWING_STAND_BLOCK, 0);
  RegisterBlock(BlockIds::STONE_SLAB, 4);
  RegisterBlock(BlockIds::BRICK_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 6);
  RegisterBlock(BlockIds::BRICK_BLOCK, 0);
  RegisterBlock(BlockIds::BROWN_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::BROWN_MUSHROOM, 0);
  RegisterBlock(BlockIds::BROWN_MUSHROOM_BLOCK, 0);
  RegisterBlock(BlockIds::CACTUS, 0);
  RegisterBlock(BlockIds::CAKE_BLOCK, 0);
  RegisterBlock(BlockIds::CARPET, 0);
  RegisterBlock(BlockIds::CARROTS, 0);
  RegisterBlock(BlockIds::CARVED_PUMPKIN, 0);
  RegisterBlock(BlockIds::CHEMICAL_HEAT, 0);
  RegisterBlock(BlockIds::CHEST, 2);
  RegisterBlock(BlockIds::QUARTZ_BLOCK, 1);
  RegisterBlock(BlockIds::RED_SANDSTONE, 1);
  RegisterBlock(BlockIds::SANDSTONE, 1);
  RegisterBlock(BlockIds::STONEBRICK, 3);
  RegisterBlock(BlockIds::CLAY_BLOCK, 0);
  RegisterBlock(BlockIds::COAL_BLOCK, 0);
  RegisterBlock(BlockIds::COAL_ORE, 0);
  RegisterBlock(BlockIds::COBBLESTONE, 0);
  RegisterBlock(BlockIds::STONE_SLAB, 3);
  RegisterBlock(BlockIds::COBBLESTONE_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 0);
  RegisterBlock(BlockIds::COBWEB, 0);
  RegisterBlock(BlockIds::COCOA, 0);
  RegisterBlock(BlockIds::CHEMISTRY_TABLE, 0);
  RegisterBlock(BlockIds::CONCRETE, 0);
  RegisterBlock(BlockIds::CONCRETEPOWDER, 0);
  RegisterBlock(BlockIds::CORAL, 0);
  RegisterBlock(BlockIds::CORAL_BLOCK, 0);
  RegisterBlock(BlockIds::CORAL_FAN, 0);
  RegisterBlock(BlockIds::POPPY, 9);
  RegisterBlock(BlockIds::STONEBRICK, 2);
  RegisterBlock(BlockIds::CRAFTING_TABLE, 0);
  RegisterBlock(BlockIds::RED_SANDSTONE, 2);
  RegisterBlock(BlockIds::STONE_SLAB4, 4);
  RegisterBlock(BlockIds::SANDSTONE, 2);
  RegisterBlock(BlockIds::STONE_SLAB4, 3);
  RegisterBlock(BlockIds::CYAN_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::DANDELION, 0);
  RegisterBlock(BlockIds::DARK_OAK_BUTTON, 0);
  RegisterBlock(BlockIds::DARK_OAK_DOOR_BLOCK, 0);
  RegisterBlock(BlockIds::FENCE, 5);
  RegisterBlock(BlockIds::DARK_OAK_FENCE_GATE, 0);
  RegisterBlock(BlockIds::LEAVES2, 1);
  RegisterBlock(BlockIds::LOG2, 1);
  RegisterBlock(BlockIds::PLANKS, 5);
  RegisterBlock(BlockIds::DARK_OAK_PRESSURE_PLATE, 0);
  RegisterBlock(BlockIds::SAPLING, 5);
  RegisterBlock(BlockIds::DARKOAK_STANDING_SIGN, 0);
  RegisterBlock(BlockIds::WOODEN_SLAB, 5);
  RegisterBlock(BlockIds::DARK_OAK_STAIRS, 0);
  RegisterBlock(BlockIds::DARK_OAK_TRAPDOOR, 0);
  RegisterBlock(BlockIds::DARKOAK_WALL_SIGN, 2);
  RegisterBlock(BlockIds::WOOD, 5);
  RegisterBlock(BlockIds::PRISMARINE, 1);
  RegisterBlock(BlockIds::STONE_SLAB2, 3);
  RegisterBlock(BlockIds::DARK_PRISMARINE_STAIRS, 0);
  RegisterBlock(BlockIds::DAYLIGHT_DETECTOR, 0);
  RegisterBlock(BlockIds::DEADBUSH, 0);
  RegisterBlock(BlockIds::DETECTOR_RAIL, 0);
  RegisterBlock(BlockIds::DIAMOND_BLOCK, 0);
  RegisterBlock(BlockIds::DIAMOND_ORE, 0);
  RegisterBlock(BlockIds::STONE, 3);
  RegisterBlock(BlockIds::STONE_SLAB3, 4);
  RegisterBlock(BlockIds::DIORITE_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 3);
  RegisterBlock(BlockIds::DIRT, 0);
  RegisterBlock(BlockIds::DOUBLE_PLANT, 2);
  RegisterBlock(BlockIds::DRAGON_EGG, 0);
  RegisterBlock(BlockIds::DRIED_KELP_BLOCK, 0);
  RegisterBlock(BlockIds::SHULKER_BOX, 0);
  RegisterBlock(BlockIds::ELEMENT_89, 0);
  RegisterBlock(BlockIds::ELEMENT_13, 0);
  RegisterBlock(BlockIds::ELEMENT_95, 0);
  RegisterBlock(BlockIds::ELEMENT_51, 0);
  RegisterBlock(BlockIds::ELEMENT_18, 0);
  RegisterBlock(BlockIds::ELEMENT_33, 0);
  RegisterBlock(BlockIds::ELEMENT_85, 0);
  RegisterBlock(BlockIds::ELEMENT_56, 0);
  RegisterBlock(BlockIds::ELEMENT_97, 0);
  RegisterBlock(BlockIds::ELEMENT_4, 0);
  RegisterBlock(BlockIds::ELEMENT_83, 0);
  RegisterBlock(BlockIds::ELEMENT_107, 0);
  RegisterBlock(BlockIds::ELEMENT_5, 0);
  RegisterBlock(BlockIds::ELEMENT_35, 0);
  RegisterBlock(BlockIds::ELEMENT_48, 0);
  RegisterBlock(BlockIds::ELEMENT_20, 0);
  RegisterBlock(BlockIds::ELEMENT_98, 0);
  RegisterBlock(BlockIds::ELEMENT_6, 0);
  RegisterBlock(BlockIds::ELEMENT_58, 0);
  RegisterBlock(BlockIds::ELEMENT_55, 0);
  RegisterBlock(BlockIds::ELEMENT_17, 0);
  RegisterBlock(BlockIds::ELEMENT_24, 0);
  RegisterBlock(BlockIds::ELEMENT_27, 0);
  RegisterBlock(BlockIds::CHEMISTRY_TABLE, 8);
  RegisterBlock(BlockIds::ELEMENT_112, 0);
  RegisterBlock(BlockIds::ELEMENT_29, 0);
  RegisterBlock(BlockIds::ELEMENT_96, 0);
  RegisterBlock(BlockIds::ELEMENT_110, 0);
  RegisterBlock(BlockIds::ELEMENT_105, 0);
  RegisterBlock(BlockIds::ELEMENT_66, 0);
  RegisterBlock(BlockIds::ELEMENT_99, 0);
  RegisterBlock(BlockIds::ELEMENT_68, 0);
  RegisterBlock(BlockIds::ELEMENT_63, 0);
  RegisterBlock(BlockIds::ELEMENT_100, 0);
  RegisterBlock(BlockIds::ELEMENT_114, 0);
  RegisterBlock(BlockIds::ELEMENT_9, 0);
  RegisterBlock(BlockIds::ELEMENT_87, 0);
  RegisterBlock(BlockIds::ELEMENT_64, 0);
  RegisterBlock(BlockIds::ELEMENT_31, 0);
  RegisterBlock(BlockIds::ELEMENT_32, 0);
  RegisterBlock(BlockIds::ELEMENT_79, 0);
  RegisterBlock(BlockIds::ELEMENT_72, 0);
  RegisterBlock(BlockIds::ELEMENT_108, 0);
  RegisterBlock(BlockIds::ELEMENT_2, 0);
  RegisterBlock(BlockIds::ELEMENT_67, 0);
  RegisterBlock(BlockIds::ELEMENT_1, 0);
  RegisterBlock(BlockIds::ELEMENT_49, 0);
  RegisterBlock(BlockIds::ELEMENT_53, 0);
  RegisterBlock(BlockIds::ELEMENT_77, 0);
  RegisterBlock(BlockIds::ELEMENT_26, 0);
  RegisterBlock(BlockIds::ELEMENT_36, 0);
  RegisterBlock(BlockIds::ELEMENT_57, 0);
  RegisterBlock(BlockIds::ELEMENT_103, 0);
  RegisterBlock(BlockIds::ELEMENT_82, 0);
  RegisterBlock(BlockIds::ELEMENT_3, 0);
  RegisterBlock(BlockIds::ELEMENT_116, 0);
  RegisterBlock(BlockIds::ELEMENT_71, 0);
  RegisterBlock(BlockIds::ELEMENT_12, 0);
  RegisterBlock(BlockIds::ELEMENT_25, 0);
  RegisterBlock(BlockIds::ELEMENT_109, 0);
  RegisterBlock(BlockIds::ELEMENT_101, 0);
  RegisterBlock(BlockIds::ELEMENT_80, 0);
  RegisterBlock(BlockIds::ELEMENT_42, 0);
  RegisterBlock(BlockIds::ELEMENT_115, 0);
  RegisterBlock(BlockIds::ELEMENT_60, 0);
  RegisterBlock(BlockIds::ELEMENT_10, 0);
  RegisterBlock(BlockIds::ELEMENT_93, 0);
  RegisterBlock(BlockIds::ELEMENT_28, 0);
  RegisterBlock(BlockIds::ELEMENT_113, 0);
  RegisterBlock(BlockIds::ELEMENT_41, 0);
  RegisterBlock(BlockIds::ELEMENT_7, 0);
  RegisterBlock(BlockIds::ELEMENT_102, 0);
  RegisterBlock(BlockIds::ELEMENT_118, 0);
  RegisterBlock(BlockIds::ELEMENT_76, 0);
  RegisterBlock(BlockIds::ELEMENT_8, 0);
  RegisterBlock(BlockIds::ELEMENT_46, 0);
  RegisterBlock(BlockIds::ELEMENT_15, 0);
  RegisterBlock(BlockIds::ELEMENT_78, 0);
  RegisterBlock(BlockIds::ELEMENT_94, 0);
  RegisterBlock(BlockIds::ELEMENT_84, 0);
  RegisterBlock(BlockIds::ELEMENT_19, 0);
  RegisterBlock(BlockIds::ELEMENT_59, 0);
  RegisterBlock(BlockIds::ELEMENT_61, 0);
  RegisterBlock(BlockIds::ELEMENT_91, 0);
  RegisterBlock(BlockIds::ELEMENT_88, 0);
  RegisterBlock(BlockIds::ELEMENT_86, 0);
  RegisterBlock(BlockIds::ELEMENT_75, 0);
  RegisterBlock(BlockIds::ELEMENT_45, 0);
  RegisterBlock(BlockIds::ELEMENT_111, 0);
  RegisterBlock(BlockIds::ELEMENT_37, 0);
  RegisterBlock(BlockIds::ELEMENT_44, 0);
  RegisterBlock(BlockIds::ELEMENT_104, 0);
  RegisterBlock(BlockIds::ELEMENT_62, 0);
  RegisterBlock(BlockIds::ELEMENT_21, 0);
  RegisterBlock(BlockIds::ELEMENT_106, 0);
  RegisterBlock(BlockIds::ELEMENT_34, 0);
  RegisterBlock(BlockIds::ELEMENT_14, 0);
  RegisterBlock(BlockIds::ELEMENT_47, 0);
  RegisterBlock(BlockIds::ELEMENT_11, 0);
  RegisterBlock(BlockIds::ELEMENT_38, 0);
  RegisterBlock(BlockIds::ELEMENT_16, 0);
  RegisterBlock(BlockIds::ELEMENT_73, 0);
  RegisterBlock(BlockIds::ELEMENT_43, 0);
  RegisterBlock(BlockIds::ELEMENT_52, 0);
  RegisterBlock(BlockIds::ELEMENT_117, 0);
  RegisterBlock(BlockIds::ELEMENT_65, 0);
  RegisterBlock(BlockIds::ELEMENT_81, 0);
  RegisterBlock(BlockIds::ELEMENT_90, 0);
  RegisterBlock(BlockIds::ELEMENT_69, 0);
  RegisterBlock(BlockIds::ELEMENT_50, 0);
  RegisterBlock(BlockIds::ELEMENT_22, 0);
  RegisterBlock(BlockIds::ELEMENT_74, 0);
  RegisterBlock(BlockIds::ELEMENT_92, 0);
  RegisterBlock(BlockIds::ELEMENT_23, 0);
  RegisterBlock(BlockIds::ELEMENT_54, 0);
  RegisterBlock(BlockIds::ELEMENT_70, 0);
  RegisterBlock(BlockIds::ELEMENT_39, 0);
  RegisterBlock(BlockIds::ELEMENT_0, 0);
  RegisterBlock(BlockIds::ELEMENT_30, 0);
  RegisterBlock(BlockIds::ELEMENT_40, 0);
  RegisterBlock(BlockIds::EMERALD_BLOCK, 0);
  RegisterBlock(BlockIds::EMERALD_ORE, 0);
  RegisterBlock(BlockIds::ENCHANTING_TABLE, 0);
  RegisterBlock(BlockIds::END_PORTAL_FRAME, 0);
  RegisterBlock(BlockIds::END_ROD, 0);
  RegisterBlock(BlockIds::END_STONE, 0);
  RegisterBlock(BlockIds::STONE_SLAB3, 0);
  RegisterBlock(BlockIds::END_BRICK_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 10);
  RegisterBlock(BlockIds::END_BRICKS, 0);
  RegisterBlock(BlockIds::ENDER_CHEST, 2);
  RegisterBlock(BlockIds::STONE_SLAB, 2);
  RegisterBlock(BlockIds::FARMLAND, 0);
  RegisterBlock(BlockIds::TALLGRASS, 2);
  RegisterBlock(BlockIds::FIRE, 0);
  RegisterBlock(BlockIds::FLETCHING_TABLE, 0);
  RegisterBlock(BlockIds::FLOWER_POT_BLOCK, 0);
  RegisterBlock(BlockIds::FROSTED_ICE, 0);
  RegisterBlock(BlockIds::FURNACE, 2);
  RegisterBlock(BlockIds::GLASS, 0);
  RegisterBlock(BlockIds::GLASS_PANE, 0);
  RegisterBlock(BlockIds::GLOWINGOBSIDIAN, 0);
  RegisterBlock(BlockIds::GLOWSTONE, 0);
  RegisterBlock(BlockIds::GOLD_BLOCK, 0);
  RegisterBlock(BlockIds::GOLD_ORE, 0);
  RegisterBlock(BlockIds::STONE, 1);
  RegisterBlock(BlockIds::STONE_SLAB3, 6);
  RegisterBlock(BlockIds::GRANITE_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 2);
  RegisterBlock(BlockIds::GRASS, 0);
  RegisterBlock(BlockIds::GRASS_PATH, 0);
  RegisterBlock(BlockIds::GRAVEL, 0);
  RegisterBlock(BlockIds::GRAY_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::GREEN_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::COLORED_TORCH_RG, 13);
  RegisterBlock(BlockIds::HARDENED_CLAY, 0);
  RegisterBlock(BlockIds::HARD_GLASS, 0);
  RegisterBlock(BlockIds::HARD_GLASS_PANE, 0);
  RegisterBlock(BlockIds::HAY_BALE, 0);
  RegisterBlock(BlockIds::HOPPER_BLOCK, 0);
  RegisterBlock(BlockIds::ICE, 0);
  RegisterBlock(BlockIds::MONSTER_EGG, 5);
  RegisterBlock(BlockIds::MONSTER_EGG, 1);
  RegisterBlock(BlockIds::MONSTER_EGG, 4);
  RegisterBlock(BlockIds::MONSTER_EGG, 3);
  RegisterBlock(BlockIds::MONSTER_EGG, 0);
  RegisterBlock(BlockIds::MONSTER_EGG, 2);
  RegisterBlock(BlockIds::INFO_UPDATE, 0);
  RegisterBlock(BlockIds::INFO_UPDATE2, 0);
  RegisterBlock(BlockIds::INVISIBLEBEDROCK, 0);
  RegisterBlock(BlockIds::IRON_BLOCK, 0);
  RegisterBlock(BlockIds::IRON_BARS, 0);
  RegisterBlock(BlockIds::IRON_DOOR_BLOCK, 0);
  RegisterBlock(BlockIds::IRON_ORE, 0);
  RegisterBlock(BlockIds::IRON_TRAPDOOR, 0);
  RegisterBlock(BlockIds::FRAME_BLOCK, 0);
  RegisterBlock(BlockIds::JUKEBOX, 0);
  RegisterBlock(BlockIds::JUNGLE_BUTTON, 0);
  RegisterBlock(BlockIds::JUNGLE_DOOR_BLOCK, 0);
  RegisterBlock(BlockIds::FENCE, 3);
  RegisterBlock(BlockIds::JUNGLE_FENCE_GATE, 0);
  RegisterBlock(BlockIds::LEAVES, 3);
  RegisterBlock(BlockIds::LOG, 3);
  RegisterBlock(BlockIds::PLANKS, 3);
  RegisterBlock(BlockIds::JUNGLE_PRESSURE_PLATE, 0);
  RegisterBlock(BlockIds::SAPLING, 3);
  RegisterBlock(BlockIds::JUNGLE_STANDING_SIGN, 0);
  RegisterBlock(BlockIds::WOODEN_SLAB, 3);
  RegisterBlock(BlockIds::JUNGLE_STAIRS, 0);
  RegisterBlock(BlockIds::JUNGLE_TRAPDOOR, 0);
  RegisterBlock(BlockIds::JUNGLE_WALL_SIGN, 2);
  RegisterBlock(BlockIds::WOOD, 3);
  RegisterBlock(BlockIds::CHEMISTRY_TABLE, 12);
  RegisterBlock(BlockIds::LADDER, 2);
  RegisterBlock(BlockIds::LANTERN, 0);
  RegisterBlock(BlockIds::LAPIS_BLOCK, 0);
  RegisterBlock(BlockIds::LAPIS_ORE, 0);
  RegisterBlock(BlockIds::DOUBLE_PLANT, 3);
  RegisterBlock(BlockIds::FLOWING_LAVA, 0);
  RegisterBlock(BlockIds::LECTERN, 0);
  RegisterBlock(BlockIds::STONECUTTER, 0);
  RegisterBlock(BlockIds::LEVER, 0);
  RegisterBlock(BlockIds::LIGHT_BLUE_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::SILVER_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::DOUBLE_PLANT, 1);
  RegisterBlock(BlockIds::POPPY, 10);
  RegisterBlock(BlockIds::LILY_PAD, 0);
  RegisterBlock(BlockIds::LIME_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::JACK_O_LANTERN, 0);
  RegisterBlock(BlockIds::LOOM, 0);
  RegisterBlock(BlockIds::MAGENTA_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::MAGMA, 0);
  RegisterBlock(BlockIds::CHEMISTRY_TABLE, 4);
  RegisterBlock(BlockIds::MELON_BLOCK, 0);
  RegisterBlock(BlockIds::MELON_STEM, 0);
  RegisterBlock(BlockIds::MOB_HEAD_BLOCK, 2);
  RegisterBlock(BlockIds::MOB_SPAWNER, 0);
  RegisterBlock(BlockIds::MOSSY_COBBLESTONE, 0);
  RegisterBlock(BlockIds::STONE_SLAB2, 5);
  RegisterBlock(BlockIds::MOSSY_COBBLESTONE_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 1);
  RegisterBlock(BlockIds::STONE_SLAB4, 0);
  RegisterBlock(BlockIds::MOSSY_STONE_BRICK_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 8);
  RegisterBlock(BlockIds::STONEBRICK, 1);
  RegisterBlock(BlockIds::BROWN_MUSHROOM_BLOCK, 10);
  RegisterBlock(BlockIds::MYCELIUM, 0);
  RegisterBlock(BlockIds::NETHER_BRICK_FENCE, 0);
  RegisterBlock(BlockIds::STONE_SLAB, 7);
  RegisterBlock(BlockIds::NETHER_BRICK_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 9);
  RegisterBlock(BlockIds::NETHER_BRICK_BLOCK, 0);
  RegisterBlock(BlockIds::PORTAL, 1);
  RegisterBlock(BlockIds::NETHER_QUARTZ_ORE, 0);
  RegisterBlock(BlockIds::NETHERREACTOR, 0);
  RegisterBlock(BlockIds::NETHER_WART_PLANT, 0);
  RegisterBlock(BlockIds::NETHER_WART_BLOCK, 0);
  RegisterBlock(BlockIds::NETHERRACK, 0);
  RegisterBlock(BlockIds::NOTEBLOCK, 0);
  RegisterBlock(BlockIds::WOODEN_BUTTON, 0);
  RegisterBlock(BlockIds::OAK_DOOR_BLOCK, 0);
  RegisterBlock(BlockIds::FENCE, 0);
  RegisterBlock(BlockIds::FENCE_GATE, 0);
  RegisterBlock(BlockIds::LEAVES, 0);
  RegisterBlock(BlockIds::LOG, 0);
  RegisterBlock(BlockIds::PLANKS, 0);
  RegisterBlock(BlockIds::WOODEN_PRESSURE_PLATE, 0);
  RegisterBlock(BlockIds::SAPLING, 0);
  RegisterBlock(BlockIds::SIGN_POST, 0);
  RegisterBlock(BlockIds::WOODEN_SLAB, 0);
  RegisterBlock(BlockIds::OAK_STAIRS, 0);
  RegisterBlock(BlockIds::TRAPDOOR, 0);
  RegisterBlock(BlockIds::WALL_SIGN, 2);
  RegisterBlock(BlockIds::WOOD, 0);
  RegisterBlock(BlockIds::OBSIDIAN, 0);
  RegisterBlock(BlockIds::ORANGE_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::POPPY, 5);
  RegisterBlock(BlockIds::POPPY, 8);
  RegisterBlock(BlockIds::PACKED_ICE, 0);
  RegisterBlock(BlockIds::DOUBLE_PLANT, 5);
  RegisterBlock(BlockIds::PINK_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::POPPY, 7);
  RegisterBlock(BlockIds::PODZOL, 0);
  RegisterBlock(BlockIds::STONE, 6);
  RegisterBlock(BlockIds::STONE_SLAB3, 2);
  RegisterBlock(BlockIds::POLISHED_ANDESITE_STAIRS, 0);
  RegisterBlock(BlockIds::STONE, 4);
  RegisterBlock(BlockIds::STONE_SLAB3, 5);
  RegisterBlock(BlockIds::POLISHED_DIORITE_STAIRS, 0);
  RegisterBlock(BlockIds::STONE, 2);
  RegisterBlock(BlockIds::STONE_SLAB3, 7);
  RegisterBlock(BlockIds::POLISHED_GRANITE_STAIRS, 0);
  RegisterBlock(BlockIds::POPPY, 0);
  RegisterBlock(BlockIds::POTATOES, 0);
  RegisterBlock(BlockIds::GOLDEN_RAIL, 0);
  RegisterBlock(BlockIds::PRISMARINE, 0);
  RegisterBlock(BlockIds::PRISMARINE, 2);
  RegisterBlock(BlockIds::STONE_SLAB2, 4);
  RegisterBlock(BlockIds::PRISMARINE_BRICKS_STAIRS, 0);
  RegisterBlock(BlockIds::STONE_SLAB2, 2);
  RegisterBlock(BlockIds::PRISMARINE_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 11);
  RegisterBlock(BlockIds::PUMPKIN, 0);
  RegisterBlock(BlockIds::PUMPKIN_STEM, 0);
  RegisterBlock(BlockIds::PURPLE_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::COLORED_TORCH_BP, 13);
  RegisterBlock(BlockIds::PURPUR_BLOCK, 0);
  RegisterBlock(BlockIds::PURPUR_BLOCK, 2);
  RegisterBlock(BlockIds::STONE_SLAB2, 1);
  RegisterBlock(BlockIds::PURPUR_STAIRS, 0);
  RegisterBlock(BlockIds::QUARTZ_BLOCK, 0);
  RegisterBlock(BlockIds::QUARTZ_BLOCK, 2);
  RegisterBlock(BlockIds::STONE_SLAB, 6);
  RegisterBlock(BlockIds::QUARTZ_STAIRS, 0);
  RegisterBlock(BlockIds::RAIL, 0);
  RegisterBlock(BlockIds::RED_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::RED_MUSHROOM, 0);
  RegisterBlock(BlockIds::RED_MUSHROOM_BLOCK, 0);
  RegisterBlock(BlockIds::STONE_SLAB2, 7);
  RegisterBlock(BlockIds::RED_NETHER_BRICK_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 13);
  RegisterBlock(BlockIds::RED_NETHER_BRICK, 0);
  RegisterBlock(BlockIds::SAND, 1);
  RegisterBlock(BlockIds::RED_SANDSTONE, 0);
  RegisterBlock(BlockIds::STONE_SLAB2, 0);
  RegisterBlock(BlockIds::RED_SANDSTONE_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 12);
  RegisterBlock(BlockIds::COLORED_TORCH_RG, 5);
  RegisterBlock(BlockIds::POPPY, 4);
  RegisterBlock(BlockIds::REDSTONE_BLOCK, 0);
  RegisterBlock(BlockIds::COMPARATOR_BLOCK, 0);
  RegisterBlock(BlockIds::REDSTONE_LAMP, 0);
  RegisterBlock(BlockIds::REDSTONE_ORE, 0);
  RegisterBlock(BlockIds::REPEATER_BLOCK, 0);
  RegisterBlock(BlockIds::LIT_REDSTONE_TORCH, 5);
  RegisterBlock(BlockIds::REDSTONE_WIRE, 0);
  RegisterBlock(BlockIds::RESERVED6, 0);
  RegisterBlock(BlockIds::DOUBLE_PLANT, 4);
  RegisterBlock(BlockIds::SAND, 0);
  RegisterBlock(BlockIds::SANDSTONE, 0);
  RegisterBlock(BlockIds::STONE_SLAB, 1);
  RegisterBlock(BlockIds::SANDSTONE_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 5);
  RegisterBlock(BlockIds::SEALANTERN, 0);
  RegisterBlock(BlockIds::SEA_PICKLE, 0);
  RegisterBlock(BlockIds::UNDYED_SHULKER_BOX, 0);
  RegisterBlock(BlockIds::SLIME, 0);
  RegisterBlock(BlockIds::SMOKER, 2);
  RegisterBlock(BlockIds::QUARTZ_BLOCK, 3);
  RegisterBlock(BlockIds::STONE_SLAB4, 1);
  RegisterBlock(BlockIds::SMOOTH_QUARTZ_STAIRS, 0);
  RegisterBlock(BlockIds::RED_SANDSTONE, 3);
  RegisterBlock(BlockIds::STONE_SLAB3, 1);
  RegisterBlock(BlockIds::SMOOTH_RED_SANDSTONE_STAIRS, 0);
  RegisterBlock(BlockIds::SANDSTONE, 3);
  RegisterBlock(BlockIds::STONE_SLAB2, 6);
  RegisterBlock(BlockIds::SMOOTH_SANDSTONE_STAIRS, 0);
  RegisterBlock(BlockIds::SMOOTH_STONE, 0);
  RegisterBlock(BlockIds::STONE_SLAB, 0);
  RegisterBlock(BlockIds::SNOW, 0);
  RegisterBlock(BlockIds::SNOW_LAYER, 0);
  RegisterBlock(BlockIds::SOUL_SAND, 0);
  RegisterBlock(BlockIds::SPONGE, 0);
  RegisterBlock(BlockIds::SPRUCE_BUTTON, 0);
  RegisterBlock(BlockIds::SPRUCE_DOOR_BLOCK, 0);
  RegisterBlock(BlockIds::FENCE, 1);
  RegisterBlock(BlockIds::SPRUCE_FENCE_GATE, 0);
  RegisterBlock(BlockIds::LEAVES, 1);
  RegisterBlock(BlockIds::LOG, 1);
  RegisterBlock(BlockIds::PLANKS, 1);
  RegisterBlock(BlockIds::SPRUCE_PRESSURE_PLATE, 0);
  RegisterBlock(BlockIds::SAPLING, 1);
  RegisterBlock(BlockIds::SPRUCE_STANDING_SIGN, 0);
  RegisterBlock(BlockIds::WOODEN_SLAB, 1);
  RegisterBlock(BlockIds::SPRUCE_STAIRS, 0);
  RegisterBlock(BlockIds::SPRUCE_TRAPDOOR, 0);
  RegisterBlock(BlockIds::SPRUCE_WALL_SIGN, 2);
  RegisterBlock(BlockIds::WOOD, 1);
  RegisterBlock(BlockIds::STAINED_CLAY, 0);
  RegisterBlock(BlockIds::STAINED_GLASS, 0);
  RegisterBlock(BlockIds::STAINED_GLASS_PANE, 0);
  RegisterBlock(BlockIds::HARD_STAINED_GLASS, 0);
  RegisterBlock(BlockIds::HARD_STAINED_GLASS_PANE, 0);
  RegisterBlock(BlockIds::STONE, 0);
  RegisterBlock(BlockIds::STONE_SLAB, 5);
  RegisterBlock(BlockIds::STONE_BRICK_STAIRS, 0);
  RegisterBlock(BlockIds::COBBLESTONE_WALL, 7);
  RegisterBlock(BlockIds::STONEBRICK, 0);
  RegisterBlock(BlockIds::STONE_BUTTON, 0);
  RegisterBlock(BlockIds::STONE_PRESSURE_PLATE, 0);
  RegisterBlock(BlockIds::STONE_SLAB4, 2);
  RegisterBlock(BlockIds::NORMAL_STONE_STAIRS, 0);
  RegisterBlock(BlockIds::STONECUTTER_BLOCK, 2);
  RegisterBlock(BlockIds::STRIPPED_ACACIA_LOG, 0);
  RegisterBlock(BlockIds::WOOD, 12);
  RegisterBlock(BlockIds::STRIPPED_BIRCH_LOG, 0);
  RegisterBlock(BlockIds::WOOD, 10);
  RegisterBlock(BlockIds::STRIPPED_DARK_OAK_LOG, 0);
  RegisterBlock(BlockIds::WOOD, 13);
  RegisterBlock(BlockIds::STRIPPED_JUNGLE_LOG, 0);
  RegisterBlock(BlockIds::WOOD, 11);
  RegisterBlock(BlockIds::STRIPPED_OAK_LOG, 0);
  RegisterBlock(BlockIds::WOOD, 8);
  RegisterBlock(BlockIds::STRIPPED_SPRUCE_LOG, 0);
  RegisterBlock(BlockIds::WOOD, 9);
  RegisterBlock(BlockIds::REEDS_BLOCK, 0);
  RegisterBlock(BlockIds::DOUBLE_PLANT, 0);
  RegisterBlock(BlockIds::SWEET_BERRY_BUSH, 0);
  RegisterBlock(BlockIds::TALLGRASS, 1);
  RegisterBlock(BlockIds::TNT, 0);
  RegisterBlock(BlockIds::TORCH, 5);
  RegisterBlock(BlockIds::TRAPPED_CHEST, 2);
  RegisterBlock(BlockIds::TRIPWIRE, 0);
  RegisterBlock(BlockIds::TRIPWIRE_HOOK, 0);
  RegisterBlock(BlockIds::UNDERWATER_TORCH, 5);
  RegisterBlock(BlockIds::VINE, 0);
  RegisterBlock(BlockIds::WALL_BANNER, 2);
  RegisterBlock(BlockIds::CORAL_FAN_HANG, 0);
  RegisterBlock(BlockIds::FLOWING_WATER, 0);
  RegisterBlock(BlockIds::STILL_WATER, 0);
  RegisterBlock(BlockIds::STILL_LAVA, 0);
  RegisterBlock(BlockIds::HEAVY_WEIGHTED_PRESSURE_PLATE, 0);
  RegisterBlock(BlockIds::LIGHT_WEIGHTED_PRESSURE_PLATE, 0);
  RegisterBlock(BlockIds::WHEAT_BLOCK, 0);
  RegisterBlock(BlockIds::WHITE_GLAZED_TERRACOTTA, 2);
  RegisterBlock(BlockIds::POPPY, 6);
  RegisterBlock(BlockIds::WOOL, 0);
  RegisterBlock(BlockIds::YELLOW_GLAZED_TERRACOTTA, 2);
}
